name: Tests
on: push
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 'v14.21.3'
      - name: Deps
        run: npm ci
      - name: Env
        run: export NODE_OPTIONS=--openssl-legacy-provider
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Start server and perform E2E tests
        run: npm run server:e2e
      - name: Perform unit tests
        run: npm run test