name: Tests
on: push
jobs:
  run_tests:
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: --openssl-legacu-provider
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 'v18.20.8'
      - name: Deps
        run: npm install --legacy-peer-deps
      - name: Install specific @types/react version
        run: npm install --force @types/react@17.0.1
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Start server and perform E2E tests
        run: npm run server:e2e
      - name: Perform unit tests
        run: npm run test